; Implementation specific parameters
; These parameters must be set by the implementor according to the
; relevant profile specification.
; Values used here are based on SHA-256 and HMAC-SHA256
uint16 = 0...65536
; Arbitrary length binary data
binary_data = bstr .size (0...2048)
; binary data of length PROFILE_LEN_DIGEST
digest_data = bstr .size 32
; binary data of length PROFILE_LEN_KSYM
ksym_data = bstr .size 32
; binary data of length PROFILE_LEN_KPUB
kpub_data = bstr .size 0
; binary data of length PROFILE_LEN_SIGN
sign_data = bstr .size 32
; bit mask selecting PCRs and TSRs
reg_select_type = uint .size 4
; index of a PCR or TSR
reg_index_type = uint .size 1
; End of implementation specific parameters

; MARS Command Codes
CC_SelfTest =            0
CC_CapabilityGet =       1
CC_SequenceHash =        2
CC_SequenceUpdate =      3
CC_SequenceComplete =    4
CC_PcrExtend =           5
CC_RegRead =             6
CC_Derive =              7
CC_DpDerive =            8
CC_PublicRead =          9
CC_Quote =               10
CC_Sign =                11
CC_SignatureVerify =     12

; MARS Response Codes
rc_success = 0
rc_io      = 1
rc_failure = 2
rc_buffer  = 4
rc_command = 5
rc_value   = 6
rc_reg     = 7
rc_seq     = 8

; MARS Capability Property Tags
; number of consecutive PCRs implemented on this MARS
PT_PCR =        1
; number of consecutive TSRs implemented on this MARS
PT_TSR =        2
; size of a digest that can be processed or produced
PT_LEN_DIGEST = 3
; size of signature produced by CryptSign()
PT_LEN_SIGN =   4
; size of symmetric key produced by CryptSkdf()
PT_LEN_KSYM =   5
; size of asymmetric key returned by PublicRead()
PT_LEN_KPUB =   6
; size of private asymmetric key produced by CryptAkdf()
PT_LEN_KPRV =   7
; TCG-registered algorithm for hashing by CryptHash()
PT_ALG_HASH =   8
; TCG-registered algorithm for signing by CryptSign()
PT_ALG_SIGN =   9
; TCG-registered algorithm for symmetric key derivation by CryptSkdf()
PT_ALG_SKDF =   10
; TCG-registered algorithm for asymmetric key derivation by CryptAkdf()
PT_ALG_AKDF =   11

SelfTest = (
    CC_SelfTest,
    full_test: bool,
)

SelfTest_Rsp = (
    rc_success /
    rc_failure
)

CapabilityGet = (
     CC_CapabilityGet,
     capability:    PT_PCR /
                    PT_TSR /
                    PT_LEN_DIGEST /
                    PT_LEN_SIGN /
                    PT_LEN_KSYM /
                    PT_LEN_KPUB /
                    PT_LEN_KPRV /
                    PT_ALG_HASH /
                    PT_ALG_SIGN /
                    PT_ALG_SKDF /
                    PT_ALG_AKDF,
)

CapabilityGet_Rsp = (
    (rc_success,
    capability_data: uint16) /
    rc_value /
    rc_buffer
)

SequenceHash = (
     code: CC_SequenceHash,
)

SequenceHash_Rsp = (
    rc_success /
    rc_seq /
    rc_command /
    rc_failure
)

SequenceUpdate = (
     CC_SequenceUpdate,
     binary_data,
)

SequenceUpdate_Rsp = (
    (rc_success,
    binary_data) /
    rc_seq /
    rc_buffer /
    rc_command /
    rc_failure
)

SequenceComplete = (
     CC_SequenceComplete,
)

SequenceComplete_Rsp = (
    (rc_success,
    binary_data) /
    rc_seq /
    rc_buffer /
    rc_command /
    rc_failure
)

PcrExtend = (
    CC_PcrExtend,
    reg_index: reg_index_type,
    digest_data,
)

PcrExtend_Rsp = (
    rc_success /
    rc_reg /
    rc_buffer /
    rc_command /
    rc_failure
)

RegRead = (
    CC_RegRead,
    reg_index: reg_index_type,
)

RegRead_Rsp = (
    (rc_success,
    digest_data) /
    rc_reg /
    rc_buffer /
    rc_command /
    rc_failure
)

Derive = (
    CC_Derive,
    reg_select: reg_select_type,
    context: binary_data
)

Derive_Rsp = (
    (rc_success,
    ksym_data) /
    rc_reg /
    rc_buffer /
    rc_command /
    rc_failure
)

DpDerive = (
    CC_DpDerive,
    reg_select: reg_select_type,
    context: nil / binary_data
)

DpDerive_Rsp = (
    rc_success /
    rc_reg /
    rc_buffer /
    rc_command /
    rc_failure
)

PublicRead = (
    CC_PublicRead,
    retricted: bool,
    context: binary_data,
)

PublicRead_Rsp = (
    (rc_success,
    kpub_data) /
    rc_buffer /
    rc_command /
    rc_failure
)

Quote = (
    CC_Quote,
    reg_select: reg_select_type,
    nonce: digest_data,
    context: binary_data
)

Quote_Rsp = (
    (rc_success,
    sign_data) /
    rc_reg /
    rc_buffer /
    rc_command /
    rc_failure
)

Sign = (
    CC_Sign,
    context: binary_data,
    digest: digest_data,
)

Sign_Rsp = (
    (rc_success,
    sign_data) /
    rc_buffer /
    rc_command /
    rc_failure
)

SignatureVerify = (
    CC_SignatureVerify,
    retricted: bool,
    context: binary_data,
    digest: digest_data,
    signature: sign_data,
)

SignatureVerify_Rsp = (
    (rc_success,
    bool) /
    rc_buffer /
    rc_command /
    rc_failure
)

; MARS Command
mars_command = [
        SelfTest /
        CapabilityGet /
        SequenceHash /
        SequenceUpdate /
        SequenceComplete /
        PcrExtend /
        RegRead /
        Derive /
        DpDerive /
        PublicRead /
        Quote /
        Sign /
        SignatureVerify
]

; MARS Response
; Due to pattern matching processing, the order of the response codes
; is important.  The most specific response code must be first.
; This type is for convinience of validation. Implementation should
; use the specific response types bound to the command.
mars_response = [
    rc:
        PublicRead_Rsp /
        Quote_Rsp /
        Sign_Rsp /
        RegRead_Rsp /
        SignatureVerify_Rsp /
        Derive_Rsp /
        CapabilityGet_Rsp /
        SequenceUpdate_Rsp /
        SequenceComplete_Rsp /
        SelfTest_Rsp /
        SequenceHash_Rsp /
        PcrExtend_Rsp /
        DpDerive_Rsp
]
